### ISSUE TITLE
Empty list with Oracle database

### ISSUE THREAD

**Issue by RomE-HK** [SShnoodles/db2j-ce-idea-plugin#1]
Hi!
In my case after successful connection there is no schemas or tables. Just database line.
![image](https://user-images.githubusercontent.com/12252901/79466055-be59c480-8004-11ea-896b-bd005f8a841c.png)

**Comment by SShnoodles** [comment]
read db use username for schema, so r u the schema is not same to username?

**Comment by SShnoodles** [comment]
oh, my jdbc code is use username for schema. so the schema need to same
username at this version.

**Comment by RomE-HK** [comment]
> 
> 
> read db use username for schema, so r u the schema is not same to username?

Yeah. They are different. And I can log only with that user, but I able to view tables of other users

**Comment by SShnoodles** [comment]
ok, next version will support.

**Comment by RomE-HK** [comment]
Great! Thank you!

**Comment by RomE-HK** [comment]
Great! Thank you!
